import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "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")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
OPENAI_FINDER_MODEL = os.getenv("OPENAI_FINDER_MODEL", "gpt-5")
OPENAI_VALIDATOR_MODEL = os.getenv("OPENAI_VALIDATOR_MODEL", "gpt-4o-mini")
HTTP_PROXY = os.getenv("HTTP_PROXY")
HTTPS_PROXY = os.getenv("HTTPS_PROXY")
USE_UNDETECTED_CHROMEDRIVER = True
CHROME_BINARY_PATH = os.getenv("CHROME_BINARY_PATH")
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")   
ELSEVIER_API_KEY = "2d31fe14f0537435225c33d2b56fa02f"
